version: 2.1

jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t florisvdg/hello-world:${CIRCLE_SHA1:0:7} .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push florisvdg/hello-world:${CIRCLE_SHA1:0:7}
workflows:
  deploy:
    jobs:
      - publish
