version: 2.1

environment:
  TEST_SECRET_1: test_secret_1

commands:
  load-secrets:
    steps:
      - run: 
          command: |
            mkdir -p /tmp/parameterstore
            echo "export TEST_SECRET_1=test_secret_1" >> /tmp/parameterstore/PARAMETERSTORESOURCEFILE
            source /tmp/parameterstore/PARAMETERSTORESOURCEFILE
            printenv

jobs:
  print-env:
    docker:
      - image: cimg/base:stable
    steps:
      - load-secrets
      - run: printenv

workflows:
  test:
    jobs:
      - print-env
