version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20
  secrethub: secrethub/cli@dev:5a9d572

jobs:
  myjob-shell:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: secrethub://florisvdg/demo/aws/secret_access_key
      AWS_ACCESS_KEY_ID: secrethub://florisvdg/demo/aws/access_key_id
    steps:
      - secrethub/install
      - checkout
      - run: env | grep AWS_SECRET_ACCESS_KEY
      - aws-cli/setup

  myjob-exec:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_ACCESS_KEY_ID: secrethub://florisvdg/demo/aws/access_key_id
      AWS_SECRET_ACCESS_KEY: secrethub://florisvdg/demo/aws/secret_access_key
    steps:
      - checkout
      - secrethub/exec:
          command: |
            echo "This value will be masked: $AWS_ACCESS_KEY_ID"
            echo "This value will be masked: $AWS_SECRET_ACCESS_KEY"
workflows:
  main:
    jobs:
      - myjob-shell
      - myjob-exec
