version: 2.1

orbs:
  secrethub:
    executors:
      default:
        docker:
          - image: cimg/base:2020.01
    commands:
      install:
        parameters:
          shell:
            type: string
            default: /bin/sh
        steps:
          - run:
              command: |
                curl -sSfL https://github.com/secrethub/secrethub-cli/releases/download/v$VERSION/secrethub-v$VERSION-linux-amd64.tar.gz | tar zxf - -C $HOME
                echo 'export SHELL="secrethub run -- $SHELL"' >> $BASH_ENV
              shell: << parameters.shell >>
              environment:
                VERSION: 0.34.0
    jobs:
      run:
        executor: default
        parameters:
          command:
            type: steps
            default: []
        shell: secrethub run -- /bin/sh
        steps:
          - install
          - run: secrethub --version
          - steps: << parameters.command >>

jobs:
  myjob:
    docker:
      - image: cimg/base:2020.01
    shell: secrethub run -- /bin/sh
    steps:
      - secrethub/install
      - checkout
      - run: echo $SHELL
      - run: echo $BASH_ENV
      - run: ls -a ~/
      - run: env

workflows:
  main:
    jobs:
      - myjob
