version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20
  secrethub: secrethub/cli@dev:latest

jobs:
  myjob:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - secrethub/install
      - checkout
      - run: echo $SHELL
      - run: env | grep AWS_SECRET_ACCESS_KEY
      - aws-cli/setup

workflows:
  main:
    jobs:
      - myjob
