version: 2.1

environment:
  TEST_SECRET_1: test_secret_1

commands:
  load-secrets:
    steps:
      - run: 
          environment:
            TEST_SECRET_2: test_secret_2
            TEST_SECRET_3: test_secret_3
          command: |
            echo "export TEST_SECRET_1=$TEST_SECRET_1" >> $BASH_ENV
            echo "export TEST_SECRET_2=$TEST_SECRET_2" >> $BASH_ENV
            echo "export TEST_SECRET_3=$TEST_SECRET_3" >> $BASH_ENV

jobs:
  print-env:
    docker:
      - image: cimg/base:stable
    steps:
      - run: cat $BASH_ENV
      - run: printenv

workflows:
  test:
    jobs:
      - print-env:
          pre-steps:
            - load-secrets
