version: 2.1

orbs:
  secrethub:
    executors:
      default:
        docker:
          - image: cimg/base:2020.01
    commands:
      install:
        steps:
          - run:
              command: curl -sSfL https://github.com/secrethub/secrethub-cli/releases/download/v$VERSION/secrethub-v$VERSION-linux-amd64.tar.gz | tar zxf - -C $HOME
              shell: /bin/sh
              environment:
                VERSION: 0.34.0
    jobs:
      run:
        executor: default
        parameters:
          command:
            type: steps
            default: []
        shell: secrethub run -- /bin/sh
        steps:
          - install
          - run: secrethub --version
          - steps: << parameters.command >>

workflows:
  main:
    jobs:
      - secrethub/run:
          command:
            - checkout
            - run: echo hello
            - run: env
