version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20
  secrethub: secrethub/cli@dev:f75be60

jobs:
  myjob-shell:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - secrethub/install
      - checkout
      - run: echo $SHELL
      - run: env | grep AWS_SECRET_ACCESS_KEY
      - aws-cli/setup
  myjob-exec:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - secrethub/exec:
          version: 0.35.0
          command: |
            printenv

workflows:
  main:
    jobs:
      - myjob-shell
      - myjob-exec
