version: 2.1
orbs:
  secrethub: secrethub/cli@dev:1f31e46

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_ACCESS_KEY_ID: secrethub://florisvdg/demo/aws/access_key_id
      AWS_SECRET_ACCESS_KEY: secrethub://florisvdg/demo/aws/secret_access_key
    steps:
      - checkout
      - secrethub/exec:
          command: |
            echo "This value will be masked: $AWS_ACCESS_KEY_ID"
            echo "This value will be masked: $AWS_SECRET_ACCESS_KEY"
workflows:
  deploy:
    jobs:
      - deploy
