version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  secrethub: secrethub/cli@dev:1f31e46

jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_USERNAME: secrethub://florisvdg/demo/docker/username
      DOCKER_PASSWORD: secrethub://florisvdg/demo/docker/password
    shell: secrethub run -- /bin/bash
    steps:
      - secrethub/install
      - checkout
      - setup_remote_docker
      - docker/build:
          step-name: Build Docker image
          image: florisvdg/hello-world
          tag: ${CIRCLE_SHA1:0:7}
      - docker/push:
          step-name: Publish Docker image
          image: florisvdg/hello-world
          tag: ${CIRCLE_SHA1:0:7}
workflows:
  deploy:
    jobs:
      - publish
