version: 2.1
orbs:
  secrethub: secrethub/cli@dev:1f31e46

jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_USERNAME: secrethub://florisvdg/demo/docker/username
      DOCKER_PASSWORD: secrethub://florisvdg/demo/docker/password
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t florisvdg/hello-world:${CIRCLE_SHA1:0:7} .
      - secrethub/exec:
          command-name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push florisvdg/hello-world:${CIRCLE_SHA1:0:7}
workflows:
  deploy:
    jobs:
      - publish
